#!/usr/bin/env bash

function version() {
  # get version from image (major.minor.micro, e.g. v4.11.0)
  version=v$( \
    oc status | grep '^pod' | \
    sed -n -r -e 's/.*(([[:digit:]])+\.([[:digit:]])+\.([[:digit:]])+).*/\1/p' \
  )

  # if version is not found, fallback to imageID
  [ -z "${version}" ] && version=$(oc status | grep '^pod.*runs' | sed -r -e 's/^pod.*runs //')

  # if version is still not found, use Unknown
  [ -z "${version}" ] && version="Unknown"

  echo ${version}
}

function image_id() {
   # get image id (e.g. repository@digest )
  image_id=$(oc status | grep '^pod' | sed -r -e 's/^pod.*runs //' | awk '{print $2}')
  
  # if image_id is not found, use Unknown
  [ -z "${image_id}" ] && image_id="Unknown"
echo ${image_id}

}
