name: Publish Container Images
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push-images:
    name: Build and push images to quay.io/medik8s
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push CSV 0.0.1 + latest images for PR merges to main
        if: ${{ github.ref_type != 'tag' }}
        run: export IMAGE_REGISTRY=quay.io/medik8s && make container-build-and-push-community

      - name: Build and push versioned CSV and images for tags
        if: ${{ github.ref_type == 'tag' }}
        # remove leading 'v' from tag!
        run: export VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//') && make container-build-and-push-community

      - name: Create release with manifests
        if: ${{ github.ref_type == 'tag' }}
        # https://github.com/marketplace/actions/github-release-create-update-and-upload-assets
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          body: |
            # Node Maintenance Operator ${{ github.ref_name }}
            
            ## Notable Changes
            
            * TODO
            ## Release Artifacts
            
            ### Images
            * Operator: quay.io/repository/medik8s/node-maintenance-operator:${{ github.ref_name }}
            * Bundle: quay.io/repository/medik8s/node-maintenance-operator-bundle:${{ github.ref_name }}
            * Catalog aka Index: quay.io/repository/medik8s/node-maintenance-operator-catalog:${{ github.ref_name }}
            
            ### Source code and OLM manifests
            Please find the source code and the OLM manifests in the `Assets` section below.
          gzip: folders
          files: >
            Manifests:bundle/
